### ISSUE TITLE
Package not found when installing this package.

### ISSUE THREAD

**Issue by jitendraP-ashutec** [alexanderschau/uniquebrowserid#2]
Hi, I am getting below error when I am installing this package and try to create uuid.

Error: ./node_modules/@otplib/plugin-crypto/index.js

If I install https://www.npmjs.com/package/@otplib/plugin-crypto package then I am getting below error:

Error: ./node_modules/@otplib/plugin-crypto/index.js
Module not found: Error: Can't resolve 'crypto

I am using angular 11.

could you please tell me how can I fix this issue

**Comment by alexanderschau** [comment]
Did `npm i uniquebrowserid` run without any problems? Because on my test everything worked well.

**Comment by jitendraP-ashutec** [comment]
No, after installing uniquebrowserid modules it give me above error.

Does you package will work if two different system has same configuration and same browser version ?

**Comment by alexanderschau** [comment]
I can't really help you with that, because I don't know how your environment looks like. Maybe [this](https://stackoverflow.com/questions/54162297/module-not-found-error-cant-resolve-crypto/54162447) could help you. If it was an error with this package you're welcome to create a PR.

> Does you package will work if two different system has same configuration and same browser version ?

Yes, that should work. You'll find some more information about that in [this post](https://dev.to/alexanderschau/secure-json-web-token-with-unique-browser-ids-3a78).
